### ISSUE TITLE
The download path breaks in OSX.

### ISSUE THREAD

**Issue by syhily** [HEIGE-PCloud/ABookDownloader#1]
![image](https://user-images.githubusercontent.com/1761698/89408236-abedcd00-d752-11ea-8ac2-085a8aafe922.png)

**Comment by HEIGE-PCloud** [comment]
Thank you for the issue reported. The bug should be resolved through commit [c4cbad2](https://github.com/HEIGE-PCloud/ABookDownloader/commit/c4cbad2a9865c92ad9df0c5f01cd34725083759d). Please delete those broken files, run `git pull` and the issue should be fixed.😊

**Comment by syhily** [comment]
Yep, the hidden files have been moved to the proper location. This issue has been resolved.
