### ISSUE TITLE
Auto re-login after login had timed out

### ISSUE THREAD

**Issue by Sam0230** [HEIGE-PCloud/ABookDownloader#14]
Download ./Downloads/生物化学原理（第3版）/第一篇 结构生物化学/第一章 氨基酸/参考文献/第一章参考文献.pdf successfully!
1 downloadable items found!
第一章推荐网址
http://abook.hep.com.cn/ICourseFiles/5000003171/resourses/2018/11/2/15411257420777201925975512566969.pdf

Download ./Downloads/生物化学原理（第3版）/第一篇 结构生物化学/第一章 氨基酸/推荐网址/第一章推荐网址.pdf successfully!
^CInfo fetched failed, will restart in 5 seconds.
^CInfo fetched failed, will restart in 5 seconds.
^CInfo fetched failed, will restart in 5 seconds.
^CInfo fetched failed, will restart in 5 seconds.
And then stoped.

**Comment by Sam0230** [comment]
How to fix: see https://github.com/HEIGE-PCloud/ABookDownloader/pull/16

**Comment by HEIGE-PCloud** [comment]
Is this error triggered by login expired instead of other network connection issues?

**Comment by Sam0230** [comment]
Yes, it is. I was able to access abook.hep.com.cn normally while it went wrong.

**Comment by HEIGE-PCloud** [comment]
From my tests, I was always able to call `get_chapter_info()` successfully with the following steps.
1. Login through ABookDownloaderCLI.py
2. Successfully executed `get_courses_info()` and `display_courses_info()`
3. Login through abook.hep.com.cn on the web browser with the same account
4. Try execute `get_chapter_info()` in ABookDownloaderCLI.py
`get_chapter_info()` returned correct information and the web login was not expired as well.

**Comment by HEIGE-PCloud** [comment]
Login through the mobile app will cause the expiration and raise `json.decoder.JSONDecodeError`.

**Comment by HEIGE-PCloud** [comment]
I think it is fine to merge the auto re-login code but I still doubt that it is not the login expiration which has caused the issue.
