### ISSUE TITLE
章节下载不完全

### ISSUE THREAD

**Issue by zjqwtm543** [HEIGE-PCloud/ABookDownloader#5]
发现每一章只下载了前20个文件，还有翻页后的部分就没检索到
加油吧

**Comment by zjqwtm543** [comment]
![image](https://user-images.githubusercontent.com/35713929/99422205-448f0e00-293a-11eb-8a0e-ad2552d6b736.png)

**Comment by zjqwtm543** [comment]
![image](https://user-images.githubusercontent.com/35713929/99422400-76a07000-293a-11eb-937b-32adf07483e7.png)

**Comment by zjqwtm543** [comment]
章节拥有第二级结构的情况下，无法获取第一级的资源信息。
资源请求还是能看到的
![image](https://user-images.githubusercontent.com/35713929/99424312-80c36e00-293c-11eb-8a8b-d9b2ecd2b0f4.png)

**Comment by HEIGE-PCloud** [comment]
可以提供temp目录下的`5000xxxxx.json`和`course_info.json`中的日志吗？

**Comment by zjqwtm543** [comment]
[temp.zip](https://github.com/HEIGE-PCloud/ABookDownloader/files/5555279/temp.zip)
好的  隐私信息稍微做了点处理 应该不影响

**Comment by zjqwtm543** [comment]
摸索了下
直接改courseResourceList.action的cur参数就行了
而且cur大于最后页码的时候返回的直接是最后页的

**Comment by HEIGE-PCloud** [comment]
可以帮忙测试吗？clone issue-5分支并尝试下载，应该能够遍历所有页面了。

**Comment by zjqwtm543** [comment]
ok  章节下载完全了 
就剩下这个有二级结构的序章拿不下了，加油

我这主要需求已经满足了，余下的问题可以慢慢来了哈

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/101951851-94868b00-3bef-11eb-9f20-6c89dcf901c5.png)
二级目录显示在GUI Dev版中解决 clone dev分支来进行试用。
